import { defineField, defineType } from "sanity";
import siteConfig from "../../config.js";
import { blankHint, imageHint } from "./hints";

const defaults = siteConfig.contact;
const settings = siteConfig.settings;

function formFieldObject(
  name: string,
  title: string,
  fieldDefaults: { label: string; required: boolean; placeholder: string },
) {
  return defineField({
    name,
    title,
    type: "object",
    fields: [
      {
        name: "label",
        title: "Label",
        type: "string",
        initialValue: fieldDefaults.label,
        validation: (Rule) => Rule.max(40),
      },
      {
        name: "placeholder",
        title: "Placeholder",
        type: "string",
        initialValue: fieldDefaults.placeholder,
        validation: (Rule) => Rule.max(160),
      },
      {
        name: "required",
        title: "Required",
        type: "boolean",
        initialValue: fieldDefaults.required,
      },
    ],
  });
}

export const contactPage = defineType({
  name: "contactPage",
  title: "Contact Page",
  type: "document",
  groups: [
    { name: "seo", title: "SEO" },
    { name: "hero", title: "Hero", default: true },
    { name: "form", title: "Form" },
    { name: "details", title: "Contact details card" },
    { name: "map", title: "Map" },
  ],
  fields: [
    defineField({
      name: "seoTitle",
      title: "SEO title",
      type: "string",
      group: "seo",
      description: blankHint,
      initialValue: defaults.seo.title,
      validation: (Rule) => Rule.max(70),
    }),
    defineField({
      name: "seoDescription",
      title: "SEO description",
      type: "text",
      rows: 3,
      group: "seo",
      description: blankHint,
      initialValue: defaults.seo.description,
      validation: (Rule) => Rule.max(180),
    }),
    defineField({
      name: "badge",
      title: "Badge",
      type: "string",
      group: "hero",
      description: blankHint,
      initialValue: defaults.badge,
      validation: (Rule) => Rule.max(40),
    }),
    defineField({
      name: "heroTitle",
      title: "Hero title",
      type: "string",
      group: "hero",
      description: blankHint,
      initialValue: defaults.heroTitle,
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: "heroSubhead",
      title: "Hero subhead",
      type: "text",
      rows: 3,
      group: "hero",
      description: blankHint,
      initialValue: defaults.heroSubhead,
      validation: (Rule) => Rule.max(400),
    }),
    defineField({
      name: "heroBackground",
      title: "Hero background image",
      type: "image",
      group: "hero",
      description: imageHint,
      options: { hotspot: true },
    }),
    defineField({
      name: "formTitle",
      title: "Form title",
      type: "string",
      group: "form",
      description: blankHint,
      initialValue: defaults.formTitle,
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: "formIntro",
      title: "Form intro",
      type: "text",
      rows: 2,
      group: "form",
      description: blankHint,
      initialValue: defaults.formIntro,
      validation: (Rule) => Rule.max(240),
    }),
    defineField({
      name: "formSubjects",
      title: "Subject options",
      type: "array",
      of: [{ type: "string" }],
      group: "form",
      initialValue: defaults.formSubjects,
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: "formFields",
      title: "Form fields",
      type: "object",
      group: "form",
      options: { collapsible: true, collapsed: false },
      fields: [
        formFieldObject("name", "Name field", defaults.formFields.name),
        formFieldObject("company", "Company field", defaults.formFields.company),
        formFieldObject("email", "Email field", defaults.formFields.email),
        formFieldObject("subject", "Subject field", defaults.formFields.subject),
        formFieldObject("message", "Message field", defaults.formFields.message),
      ],
    }),
    defineField({
      name: "submitLabel",
      title: "Submit button label",
      type: "string",
      group: "form",
      description: blankHint,
      initialValue: defaults.submitLabel,
      validation: (Rule) => Rule.max(40),
    }),
    defineField({
      name: "successMessage",
      title: "Success message",
      type: "string",
      group: "form",
      description: blankHint,
      initialValue: defaults.successMessage,
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: "detailsTitle",
      title: "Details card title",
      type: "string",
      group: "details",
      description: blankHint,
      initialValue: defaults.detailsTitle,
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: "companyName",
      title: "Company name on card",
      type: "string",
      group: "details",
      description: blankHint,
      initialValue: settings.companyName,
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      group: "details",
      description: blankHint,
      initialValue: settings.tagline,
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: "contactResponsibleName",
      title: "Responsible person name",
      type: "string",
      group: "details",
      description: blankHint,
      initialValue: settings.contact.contactResponsibleName,
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: "contactCertificate",
      title: "Certificate / credentials",
      type: "string",
      group: "details",
      description: blankHint,
      initialValue: settings.contact.contactCertificate,
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: "contactPosition",
      title: "Position",
      type: "string",
      group: "details",
      description: blankHint,
      initialValue: settings.contact.contactPosition,
      validation: (Rule) => Rule.max(140),
    }),
    defineField({
      name: "phone",
      title: "Phone",
      type: "string",
      group: "details",
      description: blankHint,
      initialValue: settings.phone,
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: "displayEmail",
      title: "Email shown on the card",
      type: "string",
      group: "details",
      description: blankHint,
      initialValue: settings.generalEmail,
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: "websiteUrl",
      title: "Website URL",
      type: "url",
      group: "details",
      description: blankHint,
      initialValue: settings.websiteUrl,
      validation: (Rule) => Rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "addressLines",
      title: "Address lines",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
      description: blankHint,
      initialValue: settings.addressLines,
      validation: (Rule) => Rule.max(6),
    }),
    defineField({
      name: "officeHours",
      title: "Office hours",
      type: "string",
      group: "details",
      description: blankHint,
      initialValue: settings.officeHours,
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: "contactLogo",
      title: "Logo on card",
      type: "image",
      group: "details",
      description: imageHint,
      options: { hotspot: true },
    }),
    defineField({
      name: "contactQrImage",
      title: "QR code image",
      type: "image",
      group: "details",
      description: imageHint,
      options: { hotspot: true },
    }),
    defineField({
      name: "mapTitle",
      title: "Map title",
      type: "string",
      group: "map",
      description: blankHint,
      initialValue: defaults.mapTitle,
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: "mapIntro",
      title: "Map intro",
      type: "text",
      rows: 2,
      group: "map",
      description: blankHint,
      initialValue: defaults.mapIntro,
      validation: (Rule) => Rule.max(240),
    }),
    defineField({
      name: "mapEmbedUrl",
      title: "Google Maps embed URL",
      type: "url",
      group: "map",
      description: blankHint,
      initialValue: defaults.mapEmbedUrl,
      validation: (Rule) => Rule.uri({ scheme: ["http", "https"] }),
    }),
  ],
  preview: {
    prepare() {
      return { title: "Contact Page", subtitle: "Hero, form, details card, and map" };
    },
  },
});
