import { defineField, defineType } from "sanity";
import siteConfig from "../../config.js";
import { blankHint, imageHint } from "./hints";

const defaults = siteConfig.homepage;

export const homePage = defineType({
  name: "homePage",
  title: "Home Page",
  type: "document",
  groups: [
    { name: "seo", title: "SEO" },
    { name: "hero", title: "Hero", default: true },
    { name: "services", title: "Services" },
    { name: "why", title: "Why GTek" },
    { name: "closing", title: "Closing CTA" },
    { name: "background", title: "Background" },
  ],
  fields: [
    defineField({
      name: "seoTitle",
      title: "SEO title",
      type: "string",
      group: "seo",
      description: blankHint,
      initialValue: defaults.seo.title,
      validation: (Rule) => Rule.max(70),
    }),
    defineField({
      name: "seoDescription",
      title: "SEO description",
      type: "text",
      rows: 3,
      group: "seo",
      description: blankHint,
      initialValue: defaults.seo.description,
      validation: (Rule) => Rule.max(180),
    }),
    defineField({
      name: "heroHeadline",
      title: "Hero headline",
      type: "string",
      group: "hero",
      description: blankHint,
      initialValue: defaults.heroHeadline,
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: "heroSubhead",
      title: "Hero subhead",
      type: "text",
      rows: 3,
      group: "hero",
      description: blankHint,
      initialValue: defaults.heroSubhead,
      validation: (Rule) => Rule.max(300),
    }),
    defineField({
      name: "heroBackground",
      title: "Hero background image",
      type: "image",
      group: "hero",
      description: imageHint,
      options: { hotspot: true },
    }),
    defineField({
      name: "heroCtaLabel",
      title: "Primary button label",
      type: "string",
      group: "hero",
      description: blankHint,
      initialValue: defaults.heroCtaLabel,
      validation: (Rule) => Rule.max(40),
    }),
    defineField({
      name: "heroCtaHref",
      title: "Primary button link",
      type: "string",
      group: "hero",
      description: blankHint,
      initialValue: defaults.heroCtaHref,
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: "heroSecondaryCtaLabel",
      title: "Secondary button label",
      type: "string",
      group: "hero",
      description: blankHint,
      initialValue: defaults.heroSecondaryCtaLabel,
      validation: (Rule) => Rule.max(40),
    }),
    defineField({
      name: "heroSecondaryCtaHref",
      title: "Secondary button link",
      type: "string",
      group: "hero",
      description: blankHint,
      initialValue: defaults.heroSecondaryCtaHref,
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: "servicesIntro",
      title: "Services intro",
      type: "string",
      group: "services",
      description: blankHint,
      initialValue: defaults.servicesIntro,
      validation: (Rule) => Rule.max(180),
    }),
    defineField({
      name: "serviceCards",
      title: "Service cards",
      type: "array",
      group: "services",
      description: "Leave empty to show the default four service cards.",
      of: [
        {
          type: "object",
          fields: [
            { name: "title", title: "Title", type: "string", validation: (Rule: any) => Rule.required().max(40) },
            { name: "description", title: "Description", type: "string", validation: (Rule: any) => Rule.required().max(200) },
            {
              name: "image",
              title: "Card image",
              type: "image",
              options: { hotspot: true },
            },
            {
              name: "showImage",
              title: "Show image",
              type: "boolean",
              description: "When enabled and an image is uploaded, the image appears on the card. Otherwise the default icon is shown.",
              initialValue: false,
            },
          ],
          preview: {
            select: { title: "title", subtitle: "description", media: "image" },
          },
        },
      ],
      initialValue: defaults.serviceCards.map((card) => ({
        title: card.title,
        description: card.description,
        showImage: card.showImage,
      })),
      validation: (Rule) => Rule.max(6),
    }),
    defineField({
      name: "whyIntro",
      title: "Why GTek intro",
      type: "string",
      group: "why",
      description: blankHint,
      initialValue: defaults.whyIntro,
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: "whyItems",
      title: "Why GTek items",
      type: "array",
      group: "why",
      description: "Leave empty to show the default items.",
      of: [
        {
          type: "object",
          fields: [
            { name: "title", title: "Title", type: "string", validation: (Rule: any) => Rule.required().max(60) },
            { name: "body", title: "Body", type: "string", validation: (Rule: any) => Rule.required().max(240) },
          ],
          preview: {
            select: { title: "title", subtitle: "body" },
          },
        },
      ],
      initialValue: defaults.whyItems,
      validation: (Rule) => Rule.max(6),
    }),
    defineField({
      name: "closingHeadline",
      title: "Closing CTA headline",
      type: "string",
      group: "closing",
      description: blankHint,
      initialValue: defaults.closingHeadline,
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: "closingSubhead",
      title: "Closing CTA subhead",
      type: "string",
      group: "closing",
      description: blankHint,
      initialValue: defaults.closingSubhead,
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: "closingCtaLabel",
      title: "Closing CTA label",
      type: "string",
      group: "closing",
      description: blankHint,
      initialValue: defaults.closingCtaLabel,
      validation: (Rule) => Rule.max(40),
    }),
    defineField({
      name: "closingCtaHref",
      title: "Closing CTA link",
      type: "string",
      group: "closing",
      description: blankHint,
      initialValue: defaults.closingCtaHref,
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: "pageBackgroundType",
      title: "Page background type",
      type: "string",
      group: "background",
      options: {
        list: [
          { title: "None", value: "none" },
          { title: "Color", value: "color" },
          { title: "Image", value: "image" },
        ],
        layout: "radio",
      },
      initialValue: defaults.pageBackgroundType,
    }),
    defineField({
      name: "pageBackgroundColor",
      title: "Page background color",
      type: "string",
      group: "background",
      description: "Hex or CSS color string used when background type is 'color'.",
      hidden: ({ parent }) => parent?.pageBackgroundType !== "color",
    }),
    defineField({
      name: "pageBackgroundImage",
      title: "Page background image",
      type: "image",
      group: "background",
      options: { hotspot: true },
      hidden: ({ parent }) => parent?.pageBackgroundType !== "image",
    }),
  ],
  preview: {
    prepare() {
      return { title: "Home Page" };
    },
  },
});
