import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  groups: [
    { name: "general", title: "General", default: true },
    { name: "contact", title: "Contact page" },
    { name: "footer", title: "Footer" },
    { name: "backgrounds", title: "Page backgrounds" },
    { name: "projects", title: "Projects page" },
  ],
  fields: [
    defineField({
      name: "companyName",
      title: "Company name",
      type: "string",
      group: "general",
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: "generalEmail",
      title: "General inquiry email",
      type: "string",
      group: "general",
      description: "Shown in footer and contact areas when no override is set.",
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: "phone",
      title: "Phone",
      type: "string",
      group: "general",
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: "websiteUrl",
      title: "Website URL",
      type: "url",
      group: "general",
      validation: (Rule) => Rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "sectors",
      title: "Sectors served",
      type: "array",
      of: [{ type: "string" }],
      group: "general",
      description: "Displayed on the homepage.",
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: "themeColors",
      title: "Theme colors",
      type: "object",
      group: "general",
      fields: [
        { name: "primary", title: "Primary color", type: "string" },
        { name: "secondary", title: "Secondary color", type: "string" },
        { name: "accent", title: "Accent color", type: "string" },
      ],
      options: { collapsible: true, collapsed: true },
    }),
    defineField({
      name: "contactEmail",
      title: "Contact form email",
      type: "string",
      group: "contact",
      description: "Receives contact form submissions (overrides environment fallback).",
      validation: (Rule) => Rule.email().max(160),
    }),
    defineField({
      name: "contactResponsibleName",
      title: "Responsible person name",
      type: "string",
      group: "contact",
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: "contactCertificate",
      title: "Certificate / Credentials",
      description: "Example: M.Eng., P.Eng.",
      type: "string",
      group: "contact",
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: "contactPosition",
      title: "Position",
      type: "string",
      group: "contact",
      validation: (Rule) => Rule.max(140),
    }),
    defineField({
      name: "contactLogo",
      title: "Contact card logo",
      description: "Logo shown on the Contact page details card.",
      type: "image",
      group: "contact",
      options: { hotspot: true },
    }),
    defineField({
      name: "contactQrImage",
      title: "QR code image",
      description: "QR code shown on the Contact page details card.",
      type: "image",
      group: "contact",
      options: { hotspot: true },
    }),
    defineField({
      name: "contactHeroBackground",
      title: "Contact hero background",
      type: "image",
      group: "contact",
      options: { hotspot: true },
    }),
    defineField({
      name: "footerTagline",
      title: "Footer tagline",
      type: "text",
      rows: 3,
      group: "footer",
      description: "Short description under the logo in the site footer.",
      validation: (Rule) => Rule.max(400),
    }),
    defineField({
      name: "footerLogo",
      title: "Footer logo",
      type: "image",
      group: "footer",
      description: "Optional. Leave empty to use the default GTek logo.",
      options: { hotspot: true },
    }),
    defineField({
      name: "footerEmail",
      title: "Footer email",
      type: "string",
      group: "footer",
      description: "Optional override. Falls back to General inquiry email.",
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: "footerLicenses",
      title: "Licenses & affiliations",
      type: "array",
      of: [{ type: "string" }],
      group: "footer",
      description: "Bullet list shown in the footer (e.g. credentials, provinces, societies).",
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: "footerCopyright",
      title: "Copyright line",
      type: "string",
      group: "footer",
      description: "Optional. Leave empty to auto-generate from company name and current year.",
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: "servicesHeroBackground",
      title: "Services hero background",
      type: "image",
      group: "backgrounds",
      options: { hotspot: true },
    }),
    defineField({
      name: "projectsHeroBackground",
      title: "Projects hero background",
      type: "image",
      group: "backgrounds",
      options: { hotspot: true },
    }),
    defineField({
      name: "projectsDisplayMode",
      title: "Projects display mode",
      type: "string",
      group: "projects",
      description: "Choose whether project cards show images or text-only layout.",
      options: {
        list: [
          { title: "With images", value: "withImage" },
          { title: "Without images", value: "withoutImage" },
        ],
        layout: "radio",
      },
      initialValue: "withImage",
    }),
  ],
  preview: {
    prepare() {
      return {
        title: "Site Settings",
        subtitle: "Company info, contact, footer & page backgrounds",
      };
    },
  },
});
