import { defineField, defineType } from "sanity";
import siteConfig from "../../config.js";
import { blankHint, imageHint } from "./hints";

const defaults = siteConfig.settings;

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  groups: [
    { name: "general", title: "General", default: true },
    { name: "contact", title: "Form email" },
    { name: "footer", title: "Footer" },
    { name: "legacy", title: "Moved to pages" },
  ],
  fields: [
    defineField({
      name: "companyName",
      title: "Company name",
      type: "string",
      group: "general",
      description: blankHint,
      initialValue: defaults.companyName,
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      group: "general",
      description: blankHint,
      initialValue: defaults.tagline,
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: "generalEmail",
      title: "General inquiry email",
      type: "string",
      group: "general",
      description: "Shown in footer and contact areas when no page override is set.",
      initialValue: defaults.generalEmail,
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: "phone",
      title: "Phone",
      type: "string",
      group: "general",
      description: blankHint,
      initialValue: defaults.phone,
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: "websiteUrl",
      title: "Website URL",
      type: "url",
      group: "general",
      initialValue: defaults.websiteUrl,
      validation: (Rule) => Rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "addressLines",
      title: "Address lines",
      type: "array",
      of: [{ type: "string" }],
      group: "general",
      initialValue: defaults.addressLines,
      validation: (Rule) => Rule.max(6),
    }),
    defineField({
      name: "officeHours",
      title: "Office hours",
      type: "string",
      group: "general",
      initialValue: defaults.officeHours,
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: "sectors",
      title: "Sectors served",
      type: "array",
      of: [{ type: "string" }],
      group: "general",
      description: "Displayed on the homepage. Leave empty to use the default list.",
      initialValue: defaults.sectors,
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: "themeColors",
      title: "Theme colors",
      type: "object",
      group: "general",
      fields: [
        { name: "primary", title: "Primary color", type: "string", initialValue: defaults.themeColors.primary },
        { name: "secondary", title: "Secondary color", type: "string", initialValue: defaults.themeColors.secondary },
        { name: "accent", title: "Accent color", type: "string", initialValue: defaults.themeColors.accent },
      ],
      options: { collapsible: true, collapsed: true },
    }),
    defineField({
      name: "contactEmail",
      title: "Contact form email (fallback)",
      type: "string",
      group: "contact",
      description: `Prefer Contact → Form recipient email (To). Used only when that field is blank. Default: ${defaults.contact.contactEmail}.`,
      initialValue: defaults.contact.contactEmail,
      validation: (Rule) => Rule.email().max(160),
    }),
    defineField({
      name: "footerTagline",
      title: "Footer tagline",
      type: "text",
      rows: 3,
      group: "footer",
      description: blankHint,
      initialValue: defaults.footer.footerTagline,
      validation: (Rule) => Rule.max(400),
    }),
    defineField({
      name: "footerLogo",
      title: "Footer logo",
      type: "image",
      group: "footer",
      description: imageHint,
      options: { hotspot: true },
    }),
    defineField({
      name: "footerEmail",
      title: "Footer email",
      type: "string",
      group: "footer",
      description: "Optional override. Falls back to General inquiry email, then the default.",
      initialValue: defaults.footer.footerEmail,
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: "footerLicenses",
      title: "Licenses & affiliations",
      type: "array",
      of: [{ type: "string" }],
      group: "footer",
      description: "Leave empty to use the default list.",
      initialValue: defaults.footer.footerLicenses,
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: "footerCopyright",
      title: "Copyright line",
      type: "string",
      group: "footer",
      description: "Optional. Leave empty to auto-generate from company name and current year.",
      initialValue: defaults.footer.footerCopyright || undefined,
      validation: (Rule) => Rule.max(200),
    }),
    defineField({
      name: "contactResponsibleName",
      title: "Responsible person name (moved)",
      type: "string",
      group: "legacy",
      hidden: true,
    }),
    defineField({
      name: "contactCertificate",
      title: "Certificate (moved)",
      type: "string",
      group: "legacy",
      hidden: true,
    }),
    defineField({
      name: "contactPosition",
      title: "Position (moved)",
      type: "string",
      group: "legacy",
      hidden: true,
    }),
    defineField({
      name: "contactLogo",
      title: "Contact logo (moved)",
      type: "image",
      group: "legacy",
      hidden: true,
    }),
    defineField({
      name: "contactQrImage",
      title: "Contact QR (moved)",
      type: "image",
      group: "legacy",
      hidden: true,
    }),
    defineField({
      name: "contactHeroBackground",
      title: "Contact hero (moved)",
      type: "image",
      group: "legacy",
      hidden: true,
    }),
    defineField({
      name: "servicesHeroBackground",
      title: "Services hero (moved)",
      type: "image",
      group: "legacy",
      hidden: true,
    }),
    defineField({
      name: "projectsHeroBackground",
      title: "Projects hero (moved)",
      type: "image",
      group: "legacy",
      hidden: true,
    }),
    defineField({
      name: "projectsDisplayMode",
      title: "Projects display mode (moved)",
      type: "string",
      group: "legacy",
      hidden: true,
    }),
  ],
  preview: {
    prepare() {
      return {
        title: "Site Settings",
        subtitle: "Company info, form email, and footer",
      };
    },
  },
});
